//! Stable environment contracts shared by providers and renderer adapters.
//!
//! Nothing in this module mentions `wgpu`. The CPU half of the environment — where the
//! sun and moon are, how bright they are, and which presentation metadata they carry — is answerable without
//! a device, and keeping it that way is what makes [`EnvironmentRequest::invalidation_since`]
//! a plain unit test instead of a headless-GPU one. The `wgpu` seam is [`crate::gpu`].

use glam::Vec3;

/// CPU result of evaluating the environment at one point in time.
///
/// The field names mirror the existing renderer lighting uniform so adapters can migrate
/// without changing its ABI. `zenith` and `horizon` remain linear RGB compatibility metadata;
/// the default sky presentation is generated by the Hillaire atmosphere LUTs.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct EnvironmentFrame {
    pub sun_direction: Vec3,
    pub moon_direction: Vec3,
    pub active_direction: Vec3,
    /// Physical RGB illuminance for the sun, independent of which celestial body is active.
    pub sun_illuminance: [f32; 3],
    /// Physical RGB illuminance for the moon.
    pub moon_illuminance: [f32; 3],
    /// Illuminance of the light currently used for direct cloud/world shading.
    pub active_illuminance: [f32; 3],
    pub active_color: [f32; 3],
    pub direct_strength: f32,
    pub ambient_strength: f32,
    /// Final environment multiplier, including the user ambient control.
    pub ambient_scale: f32,
    pub daylight: f32,
    pub moonlight: f32,
    pub zenith: [f32; 3],
    pub horizon: [f32; 3],
    pub star_rotation: f32,
}

/// Camera-relative projection data used by the aerial-perspective froxel LUT.
///
/// The basis vectors already contain the camera's FOV and aspect scaling, so
/// the environment adapter does not depend on the renderer's camera type.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FroxelCamera {
    pub forward: [f32; 3],
    pub right_scaled: [f32; 3],
    pub up_scaled: [f32; 3],
    pub near_world: f32,
    pub far_world: f32,
}

impl Default for FroxelCamera {
    fn default() -> Self {
        Self {
            forward: [1.0, 0.0, 0.0],
            right_scaled: [0.57735026, 0.0, 0.0],
            up_scaled: [0.0, 0.57735026, 0.0],
            near_world: 0.1,
            far_world: 32_000.0,
        }
    }
}

/// Everything an environment adapter needs for one frame, in renderer terms.
///
/// This type is the reason the renderer no longer touches a GPU uniform layout field by
/// field. It used to: `render.rs` copied the previous `AtmosphereUniform`, mutated nine
/// members of it, and then compared five groups of them to decide what was stale — which
/// is exactly the backend policy scattered through the renderer that the crate boundary
/// exists to prevent. Now the renderer states the environment's inputs and the adapter
/// decides what that invalidates.
///
/// The split between the physical source fields and `celestial_*`/`sky_*` metadata is not
/// redundancy: the physical sun/moon sources are shared with the atmosphere LUTs, clouds and
/// CAGI, while the metadata controls star rotation, phase and compatibility presentation knobs.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct EnvironmentRequest {
    /// Direction from a surface toward the dominant light, physical.
    pub sun_direction: [f32; 3],
    /// Top-of-atmosphere illuminance in linear scene units, physical.
    pub sun_illuminance: [f32; 3],
    /// Direction from a sample toward the physical moon, including below the horizon.
    pub moon_direction: [f32; 3],
    /// Top-of-atmosphere illuminance of the physical moon in linear scene units.
    pub moon_illuminance: [f32; 3],
    /// Direction of the light used for direct cloud/world shading. Unlike `sun_direction`, this
    /// intentionally becomes the moon at night.
    pub active_light_direction: [f32; 3],
    /// Illuminance paired with [`Self::active_light_direction`].
    pub active_light_illuminance: [f32; 3],
    /// 1 when the active light is the sun and 0 when it is the moon. Retained as an explicit
    /// source flag for consumers that need to distinguish the two direct-light regimes.
    pub active_light_is_sun: f32,
    /// Appearance-layer sun direction (`xyz`) and daylight amount (`w`).
    pub celestial_sun: [f32; 4],
    /// Appearance-layer moon direction (`xyz`) and phase (`w`).
    pub celestial_moon: [f32; 4],
    /// Compatibility zenith metadata (`rgb`) and star rotation (`w`).
    pub sky_zenith: [f32; 4],
    /// Compatibility horizon metadata (`rgb`) and moonlight amount (`w`).
    pub sky_horizon: [f32; 4],
    /// Camera position in renderer world units.
    pub camera_position: [f32; 3],
    /// Camera basis and depth range for the froxel grid.
    pub camera: FroxelCamera,
    /// Scale applied to the diffuse hemisphere term this crate returns from
    /// `environment_diffuse_radiance`.
    ///
    /// This field exists because `dispatch.wgsl` used to read `lighting.sky_ambient.w` — the
    /// *renderer's* uniform — which made this crate uncompilable without a binding it does not
    /// own. It survived because concatenating every shader into one module hides which
    /// direction a dependency runs; a `naga_oil` import graph rejected it outright as a cycle.
    ///
    /// Nothing was lost by moving it: all three of its inputs (`AMBIENT_STRENGTH`,
    /// [`crate::SunSettings::ambient_scale`] and [`EnvironmentFrame::ambient_strength`]) already
    /// live in this crate, so the renderer was only relaying a product it had no part in.
    pub ambient_scale: f32,
    /// The cloud deck: what the camera sees through and what shadows the ground.
    ///
    /// On the request rather than a second parallel channel because a cloud is not a separate
    /// environment — it is this one, with a deck in it. Splitting it would let the visible
    /// cloud and the shadow it casts be submitted out of step.
    pub clouds: crate::clouds::CloudRequest,
}

impl Default for EnvironmentRequest {
    fn default() -> Self {
        Self {
            sun_direction: [0.55, 0.8, 0.35],
            sun_illuminance: [2.2, 2.112, 1.936],
            moon_direction: [-0.55, -0.8, -0.35],
            moon_illuminance: [0.0, 0.0, 0.0],
            active_light_direction: [0.55, 0.8, 0.35],
            active_light_illuminance: [2.2, 2.112, 1.936],
            active_light_is_sun: 1.0,
            celestial_sun: [0.55, 0.8, 0.35, 1.0],
            celestial_moon: [-0.55, -0.8, -0.35, 0.85],
            sky_zenith: [0.08, 0.31, 2.55, 0.0],
            sky_horizon: [2.55, 1.37, 0.63, 0.0],
            camera_position: [0.0, 0.0, 0.0],
            camera: FroxelCamera::default(),
            // The shipped noon value: `AMBIENT_STRENGTH` with both scales at 1.0.
            ambient_scale: crate::state::AMBIENT_STRENGTH,
            clouds: crate::clouds::CloudRequest::default(),
        }
    }
}

impl EnvironmentRequest {
    /// What a transition from `previous` to `self` invalidates.
    ///
    /// Pure, and deliberately so — this is the whole update policy, and it is the part
    /// most likely to regress into "recompute everything every frame" without a test
    /// noticing. Standing still must invalidate nothing; turning the head must not
    /// re-integrate the transmittance table.
    pub fn invalidation_since(&self, previous: &Self) -> EnvironmentInvalidation {
        EnvironmentInvalidation {
            // The atmosphere's own parameters (planet radii, world scale) are not
            // per-frame inputs, so no request can invalidate them. Only a first
            // submission does, and the adapter is what knows when that is.
            atmosphere: false,
            sun: self.sun_direction != previous.sun_direction
                || self.sun_illuminance != previous.sun_illuminance
                || self.moon_direction != previous.moon_direction
                || self.moon_illuminance != previous.moon_illuminance
                || self.active_light_direction != previous.active_light_direction
                || self.active_light_illuminance != previous.active_light_illuminance
                || self.active_light_is_sun != previous.active_light_is_sun
                || self.celestial_sun != previous.celestial_sun
                || self.celestial_moon != previous.celestial_moon
                || self.sky_zenith != previous.sky_zenith
                || self.sky_horizon != previous.sky_horizon
                // Not a light change in any physical sense, but it rides in the same uniform,
                // so a changed value still has to be uploaded. Same reasoning as the
                // appearance-layer fields above.
                || self.ambient_scale != previous.ambient_scale,
            camera: self.camera_position != previous.camera_position
                || self.camera != previous.camera,
            viewer_moved: self.camera_position != previous.camera_position,
            // Deliberately narrow: the deck attenuates the sky when it is *sampled*, so a
            // coverage change costs nothing and reaches no atmosphere table. The only cached
            // cloud state is the shadow map, and this is the bit that says to redraw it.
            weather: self.clouds.invalidates_shadow_since(&previous.clouds),
        }
    }
}

/// Which class of cached environment state this frame's inputs made stale.
///
/// Stated as *what changed*, not as *which table to recompute*: a provider with a
/// different caching strategy maps these three onto its own resources. The Hillaire
/// adapter reads it as "transmittance + multiple scattering" versus "sky view + aerial
/// perspective", because only the latter pair depends on the camera.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EnvironmentInvalidation {
    /// The atmosphere's fixed parameters — first submission, or a re-configuration.
    pub atmosphere: bool,
    /// The light itself moved or changed brightness.
    pub sun: bool,
    /// The viewer moved or looked elsewhere.
    pub camera: bool,
    /// The viewer's *position* changed — a strict subset of [`Self::camera`].
    ///
    /// The distinction earns its keep exactly once, and the cloud shadow map is why: that map
    /// is world-anchored but camera-*centred*, so walking invalidates it and turning the head
    /// does not. Without this bit the choice would be redrawing it on every mouse movement or
    /// leaving a stale map centred where the viewer used to stand. In VR, where the head turns
    /// constantly and the body rarely moves, that is the difference between a per-frame pass
    /// and an occasional one.
    pub viewer_moved: bool,
    /// The cloud deck changed — coverage, shape, or its wind-advected position.
    ///
    /// Separate from `sun` because it reaches different state: the sun invalidates
    /// integrated atmosphere tables, the deck invalidates only the cloud shadow map. Folding
    /// weather into `sun` would re-integrate transmittance every time the wind moved a cloud,
    /// which is every frame.
    pub weather: bool,
}

impl EnvironmentInvalidation {
    /// Everything is stale. The correct value for a first submission.
    pub const fn all() -> Self {
        Self {
            atmosphere: true,
            sun: true,
            camera: true,
            viewer_moved: true,
            weather: true,
        }
    }

    /// Whether any GPU work is needed at all. A stationary viewer under a frozen sun
    /// answers `false`, which is the point of the whole type.
    pub const fn any(self) -> bool {
        self.atmosphere || self.sun || self.camera || self.weather
    }

    /// State independent of the viewer: stale only when the atmosphere or the light is.
    pub const fn view_independent(self) -> bool {
        self.atmosphere || self.sun
    }

    /// State that depends on where the camera is and where it points.
    pub const fn view_dependent(self) -> bool {
        self.atmosphere || self.sun || self.camera
    }

    /// State that depends on the cloud deck: the shadow map, and nothing else.
    ///
    /// Includes `sun`, because the map is a transmittance along the active-light axis — a motionless
    /// deck under a moving sun casts a different shadow. Includes `viewer_moved`, because the
    /// map is camera-*centred*. Excludes `camera`, which is the point of having both bits:
    /// turning the head must not redraw it.
    pub const fn cloud_dependent(self) -> bool {
        self.atmosphere || self.sun || self.weather || self.viewer_moved
    }

    /// Union of two invalidations, for a caller accumulating across skipped frames.
    pub const fn or(self, other: Self) -> Self {
        Self {
            atmosphere: self.atmosphere || other.atmosphere,
            sun: self.sun || other.sun,
            camera: self.camera || other.camera,
            viewer_moved: self.viewer_moved || other.viewer_moved,
            weather: self.weather || other.weather,
        }
    }
}

// There is deliberately no `EnvironmentProvider` trait. It had exactly one implementation and
// no consumer outside this crate — a placeholder in trait clothing, by this workspace's own
// rule. `HillaireEnvironment::frame` and `::settings` are plain methods; the day a second
// provider exists, the trait can be extracted from two real implementations instead of guessed
// from one.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_unchanged_frame_invalidates_nothing() {
        let request = EnvironmentRequest::default();
        assert_eq!(
            request.invalidation_since(&request),
            EnvironmentInvalidation::default()
        );
        assert!(!request.invalidation_since(&request).any());
    }

    #[test]
    fn looking_around_leaves_the_view_independent_tables_alone() {
        let previous = EnvironmentRequest::default();
        let moved = EnvironmentRequest {
            camera: FroxelCamera {
                forward: [0.0, 0.0, 1.0],
                ..FroxelCamera::default()
            },
            ..previous
        };
        let invalidation = moved.invalidation_since(&previous);
        assert!(invalidation.camera);
        assert!(!invalidation.sun);
        assert!(invalidation.view_dependent());
        assert!(!invalidation.view_independent());
    }

    #[test]
    fn moving_the_sun_invalidates_both_classes() {
        let previous = EnvironmentRequest::default();
        let sunset = EnvironmentRequest {
            sun_direction: [0.9, 0.1, 0.0],
            ..previous
        };
        let invalidation = sunset.invalidation_since(&previous);
        assert!(invalidation.sun);
        assert!(!invalidation.camera);
        assert!(invalidation.view_independent());
        assert!(invalidation.view_dependent());
    }

    /// The appearance layer is camera-only in the shader, but the renderer feeds its
    /// values through the same uniform the LUT passes read, so a palette change still
    /// has to resubmit. Treating it as a sun change is the honest answer, not a
    /// conservative one.
    #[test]
    fn appearance_only_changes_still_count_as_sun_changes() {
        let previous = EnvironmentRequest::default();
        let twilight = EnvironmentRequest {
            sky_horizon: [3.0, 0.55, 0.12, 0.0],
            ..previous
        };
        assert!(twilight.invalidation_since(&previous).sun);
    }

    #[test]
    fn first_submission_invalidates_everything() {
        let all = EnvironmentInvalidation::all();
        assert!(all.any());
        assert!(all.view_independent());
        assert!(all.view_dependent());
        assert_eq!(all.or(EnvironmentInvalidation::default()), all);
    }
}
