use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("Cargo sets manifest directory");
    let manifest_path = Path::new(&manifest_dir).join("assets/sounds.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let catalog: serde_json::Value = serde_json::from_slice(
        &std::fs::read(&manifest_path).expect("read voxel-sound asset index"),
    )
    .expect("parse voxel-sound asset index");
    let movement = &catalog["voxel_sound"]["movement"]["default"];

    let mut embedded_assets = BTreeSet::new();
    let mut generated =
        String::from("// Generated by build.rs from assets/sounds.json. Do not edit.\n");
    for (event, constant) in [
        ("footstep", "DEFAULT_FOOTSTEP"),
        ("jump", "DEFAULT_JUMP"),
        ("landing", "DEFAULT_LANDING"),
    ] {
        let paths = movement[event].as_array().unwrap_or_else(|| {
            panic!("sounds.json is missing voxel_sound.movement.default.{event}")
        });
        assert!(
            !paths.is_empty(),
            "sounds.json has no samples for voxel_sound.movement.default.{event}"
        );
        writeln!(generated, "const {constant}: [&[u8]; {}] = [", paths.len()).unwrap();
        for path in paths {
            let path = path
                .as_str()
                .unwrap_or_else(|| panic!("{event} sample path must be a string"));
            assert!(
                path.bytes().all(|byte| byte.is_ascii_alphanumeric()
                    || matches!(byte, b'/' | b'.' | b'_' | b'-')),
                "unsafe sound asset path in sounds.json: {path}"
            );
            let asset = Path::new(&manifest_dir).join("assets").join(path);
            assert!(
                asset.is_file(),
                "sounds.json indexes missing asset: {}",
                asset.display()
            );
            println!("cargo:rerun-if-changed={}", asset.display());
            embedded_assets.insert(path.to_owned());
            writeln!(
                generated,
                "    include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/{path}\")),"
            )
            .unwrap();
        }
        generated.push_str("];\n");
    }

    let output = Path::new(&std::env::var("OUT_DIR").expect("Cargo sets output directory"))
        .join("movement_assets.rs");
    std::fs::write(output, generated).expect("write generated movement asset index");

    sync_gitignore(Path::new(&manifest_dir), &embedded_assets);
}

/// Assets are ignored wholesale (`/assets/**/*.ogg`), but the files this build
/// script embeds must be committed. Keeps a generated un-ignore block in the
/// crate's .gitignore matching exactly the embedded set.
fn sync_gitignore(manifest_dir: &Path, embedded_assets: &BTreeSet<String>) {
    const BEGIN_MARKER: &str = "# BEGIN embedded assets (generated by build.rs, do not edit)";
    const END_MARKER: &str = "# END embedded assets";

    let gitignore_path = manifest_dir.join(".gitignore");
    let existing = std::fs::read_to_string(&gitignore_path).unwrap_or_default();

    let mut block = String::from(BEGIN_MARKER);
    for path in embedded_assets {
        write!(block, "\n!/assets/{path}").unwrap();
    }
    block.push('\n');
    block.push_str(END_MARKER);

    let updated = match (existing.find(BEGIN_MARKER), existing.find(END_MARKER)) {
        (Some(begin), Some(end)) if begin < end => {
            format!(
                "{}{}{}",
                &existing[..begin],
                block,
                &existing[end + END_MARKER.len()..]
            )
        }
        _ => {
            let mut base = existing.trim_end().to_string();
            if !base.is_empty() {
                base.push_str("\n\n");
            }
            format!("{base}{block}\n")
        }
    };

    if updated != existing {
        std::fs::write(&gitignore_path, updated).expect("update voxel-sound .gitignore");
    }
}
